### ISSUE TITLE
Learned cards not displaying correctly when learnt in Filtered deck.

### ISSUE THREAD

**Issue by IvorDoherty** [matthayes/anki_progress_stats#3] opened 2016-06-22 14:53 UTC
Hi again,

I sometimes use filtered decks to select cards I want to learn or review.  I have noticed that when I do so the cards are not being reflected in the "Learned Cards" graph.

For example, in this deck I learned 83 cards yesterday, and 25 today. 75 of these (50 yesterday, 25 today) were selected using filtered decks.  Only the 33 cards I learnt using "Increase today's new card limit." are showing up in the "Learned Cards" graph.  All of the learned cards are showing up in the "Review Count" and "Review Time" graphs, however.  This is the same for the other deck I do this for.

![anki-stats-2016-06-22 15-23-03](https://cloud.githubusercontent.com/assets/19647684/16270958/fad1c5cc-388f-11e6-983a-b665abbeae05.png)

The issue doesn't seem to be affecting the matured cards graph.  

Is this expected behaviour?

Thanks,

Ivor.

**Comment by matthayes** [comment] 2016-06-22 17:04
Hmm, would you mind sharing your collection with me so I can dig into the data? This is the quickest way for me to figure out what is going on.  Otherwise I'll have to try reproducing it. I haven't tested this with filtered decks before. I'm not sure if this is expected or not.

**Comment by matthayes** [comment] 2016-06-22 17:06
Also, for clarification, for the 83 and 25 cards you learned, you mean that you went through all learning steps right?

**Comment by IvorDoherty** [comment] 2016-06-23 10:17
I hope these are the files you need.

[User 1 collection without backups or media.zip](https://github.com/matthayes/anki_progress_stats/files/329681/User.1.collection.without.backups.or.media.zip)

The decks in question are:
11 Kanji Damage 
Learned 100 yesterday, 50 the day before and 25 today, via filtered decks not showing on chart (33 learnt normally showing up OK.)

12 NihongoShark.com: Kanji
Learned 30 yesterday and 19 today via filtered decks, neither showing on chart.  (One card got "learnt" twice because I accidentally rebuilt the deck before it had gone through all the steps.)

I am not currently learning new cards in the other decks.

If you need an export of these specific decks with scheduling, I can provide that, the other decks have a huge amount of media associated with them, though.

All of the cards learned are selected by a filter and I go through all the learning steps until they are returned automatically to the parent deck.

e.g:. search for "deck:12 NihongoShark.com: Kanji" is:new
Limit to 10 cards selected by order due.
Reschedule based on my answers
NO custom steps.

Thanks. :)

**Comment by matthayes** [comment] 2016-06-23 15:02
I think I see the issue.  I opened a discussion in the Anki forum [here](https://anki.tenderapp.com/discussions/ankidesktop/18726-filtered-decks-and-type).  For some reason the type isn't Learn for all the reviews.  I'm using the Learn type in the computation to determine if the card was learned, but this actually shouldn't be necessary because you can figure this out based on the interval (for cards being learned the interval is in seconds and otherwise the interval is in minutes).  It should be an easy fix.

**Comment by matthayes** [comment] 2016-06-23 15:11
I updated the [plugin](https://ankiweb.net/shared/info/266436365).  Try reinstalling and let me know if the issue is fixed.  I'll then close this if it works.  Note I saw a weird plotting issue #4 in my testing where the height of the bar doesn't look right, which is unrelated to this I think.

**Comment by matthayes** [comment] 2016-06-23 16:49
Hmm, thinking about this some more, this change may end up including relearned cards under Learned Cards.  I'll have to give this some more thought.

**Comment by IvorDoherty** [comment] 2016-06-23 20:44
I have just installed version 0.4, and I think you are right about re-learned cards.  I have learnt 40 new cards in this deck today, and it is showing nearly 100 (40 new, 1 extra new (didn't complete learning steps first time) and 55 re-learned cards)

![anki-stats-2016-06-23 21-39-38](https://cloud.githubusercontent.com/assets/19647684/16319497/775450f0-398b-11e6-9151-1ac591fb3eca.png)

**Comment by matthayes** [comment] 2016-06-23 20:50
I just posted v0.5 :)  Try installing again.  This fixes the relearn issue.  It's an imperfect workaround because I'm now including any Learn or Cram cards explicitly.  So it's basically the same as the old code but I also include Cram to include the filter decks.  I'll come up with a more robust solution later, but I think this should be more accurate.  Let me know.

**Comment by IvorDoherty** [comment] 2016-06-23 22:29
This is better. The "learnt" cards for today is showing up OK, but previous days still have extra reviews in them.

This is from the latest version (I have learnt another 10 cards since last time):

![anki-stats-2016-06-23 23-21-15](https://cloud.githubusercontent.com/assets/19647684/16322278/e5454dd6-3999-11e6-8202-d88349d5627f.png)

And this is from version 0.2, which is mostly correct until a couple of days ago when I started using filtered decks:

![anki-stats-2016-06-23 21-38-38](https://cloud.githubusercontent.com/assets/19647684/16322299/0d04de4a-399a-11e6-800b-9ecca89ad299.png)

Essentially, the graph should be the same between both except the last two or three days.

**Comment by matthayes** [comment] 2016-06-23 22:43
Hmm, I think I'll revert these changes then and go back to the 0.2 logic for now while I work on a more robust solution.  It seems like it's overall more screwed up with these changes.

**Comment by matthayes** [comment] 2016-06-23 23:09
Okay, I released 0.6, which is like 0.2 but also includes an unrelated fix for the y axes ticks.  Let me know if it doesn't look like the 0.2 behavior.  I'll work on a better fix for filtered decks.  If you can share your collection with the scheduling information that would help because I can compare it to the graphs you've shared (media isn't necessary).

**Comment by IvorDoherty** [comment] 2016-06-24 07:48
0.6 looks very similar to version 0.2.

![anki-stats-2016-06-24 08-39-22](https://cloud.githubusercontent.com/assets/19647684/16331384/fd89f614-39e7-11e6-81cf-cb94a5462a96.png)

My current collection as of this morning. (sans media.)

[User 1 collection without backups or media.zip](https://github.com/matthayes/anki_progress_stats/files/331391/User.1.collection.without.backups.or.media.zip)

Thanks! :)

**Comment by matthayes** [comment] 2016-06-25 07:02
Thanks I was able to load your collection in Anki.  I'll figure out a solution.

**Comment by matthayes** [comment] 2016-06-25 08:20
I think I have a good solution.  Compare before and after below.  Everything looks the same except for Learned Cards, where the past couple days show learned cards.  The previous days look the same.  Basically what I do now is ignore the type, which isn't reliable, and instead check for the first time the card is learned based on the interval.  I'll release a new version soon.

Before:

![ivor_orig](https://cloud.githubusercontent.com/assets/212331/16355665/bc584764-3a72-11e6-9e8d-62dfdda4f5f4.png)

After:

![ivor_new](https://cloud.githubusercontent.com/assets/212331/16355666/c42217ea-3a72-11e6-8505-4fb55ba66e34.png)

**Comment by matthayes** [comment] 2016-06-25 08:52
I released 0.7.  Give it a shot and let me know how it goes and if anything else looks weird.

**Comment by IvorDoherty** [comment] 2016-06-25 09:05
That's looking spot on in both of the decks. :)

**Comment by IvorDoherty** [comment] 2016-06-25 09:09
Can't see any new issues in any of the other stats, I think that's fixed it.  Thank you very much! :)

**Comment by matthayes** [comment] 2016-06-25 15:08
Great I'll close this then. Thanks for the assistance in fixing this.

**Closed by matthayes** 2016-06-25 15:08 UTC
