### ISSUE TITLE
Stats page won't display

### ISSUE THREAD

**Issue by IvorDoherty** [matthayes/anki_progress_stats#1] opened 2016-05-30 10:23 UTC
This was working fine yesterday when I installed it, but now I am getting an error when I click on the stats icon.  I have tried uninstalling and reinstalling without success.  Stats display OK when not installed.

Traceback (most recent call last):
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/aqt.webview", line 152, in _linkHandler
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/aqt.toolbar", line 74, in _linkHandler
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/aqt.toolbar", line 94, in _statsLinkHandler
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/aqt.main", line 732, in onStats
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/aqt.stats", line 42, in __init__
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/aqt.stats", line 89, in refresh
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/anki.stats", line 124, in report
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/anki.hooks", line 61, in repl
  File "C:\Users\<redacted>\Documents\Anki\addons\progress_stats\graphs.py", line 44, in progressGraphs
    day_cutoff_seconds=self.col.sched.dayCutoff, additional_filter=self._revlogLimit())
  File "C:\Users\<redacted>\Documents\Anki\addons\progress_stats\compute.py", line 251, in get_stats
    for bucket_index in range(min_bucket_index, max_bucket_index + 1):
TypeError: range() integer start argument expected, got NoneType.

**Comment by matthayes** [comment] 2016-05-30 15:08
Thanks for reporting this!  I'm working on a fix.

**Comment by matthayes** [comment] 2016-05-30 15:19
By the way, the issue is that it fails to get the stats when the current deck has no reviews in the review window.

**Comment by matthayes** [comment] 2016-05-30 15:53
I released a new version just now.  Please try installing [266436365](https://ankiweb.net/shared/info/266436365) again and let me know if it fixes the issue.  I'll then close this issue.  Try opening a few decks and viewing the graphs.  In particular, try opening a deck that you haven't reviewed in the last month.  The graphs should not display now instead of raising an error for this case.

**Comment by IvorDoherty** [comment] 2016-05-30 15:56
That's working. :)

**Comment by IvorDoherty** [comment] 2016-05-30 15:57
That's working. Thank you very much! :)

**Comment by matthayes** [comment] 2016-05-30 16:02
Great :)

**Closed by matthayes** 2016-05-30 16:02 UTC
Labels: bug
